void adminsignup();
void adminlogin();
void shopmenu();
void display_admin_menu();
void update_admin_menu();
void usersignup();
void userlogin();
void delete_users();
void usermenu();
void book_vehicle();
void payment(int total);
void view_car_history();